<?php
/**
 * @var \Kirill\Coins\Block\CoinAttribute $block
 */
?>
<?php $product = $block->getProduct();?>
<?php $data = explode(',',$block->getProduct()->getCoins()); ?>
<?php $show = $product->getData('isswitch'); ?>
<?php if ($show == 1): ?>
    <ul class="product-icons">
        <h5>Earn Coins+
            <?php foreach ($data as $value): ?>
                <?= (int)$value; ?>
            <?php endforeach; ?></h5>
    </ul>
<?php endif;?>
