<?php
/**
 * @var \Kirill\Coins\Block\CoinAttribute $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $price =$block->getPrice();
        $status = $block->isEnabled();
        $customerId = $block->getCustomerId();
        $percent = 100 / ($block->getPercent()) ?>
<?php if ($customerId && $status) : ?>
    <ul class="product-icons">
        <h4><?= $escaper->escapeHtml(__('You Can Earn  '))?><?= (int)($price / $percent); ?> <?= $escaper->escapeHtml(__('Coins For Buying Product'))?></h4>
    </ul>
<?php endif; ?>
