<?php
/** @var \Kirill\Coins\Block\Coins\History $block */
?>

<?php
$collection = $block->getCollection();
?>
<div class="table-wrapper coins-history">
    <table class="data table table-coins-items history" id="my-coins-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Coins')) ?></caption>
        <tbody>
        <tr>
            <th scope="col" class="col-total"><?= $block->escapeHtml(__('Total = ')) ?>
                <?= $value = $block->getCoinsValue() ?>
                <?php if ($collection->getSize() > 0) : ?>
                    <?php $size = $collection->getSize();
                    $c = 0;
                    $total = 0; ?>
                    <?php foreach ($collection as $item): ?>
                        <?php $sum = $item->getCoins();
                        $total += $sum; ?>
                    <?php endforeach; ?>
                    <?= $total ?>
                <?php endif; ?>
            </th>
        </tr>
        </tbody>
    </table>
</div>
<div class="table-wrapper coins-history">
    <table class="data table table-coins-items history" id="my-coins-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Coins')) ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col-id"><?= $block->escapeHtml(__('Transaction Id')) ?></th>
            <th scope="col" class="col-order-id"><?= $block->escapeHtml(__('Order ID')) ?></th>
            <th scope="col" class="col-comment"><?= $block->escapeHtml(__('Comment')) ?></th>
            <th scope="col" class="col-change"><?= $block->escapeHtml(__('Change')) ?></th>
            <th scope="col" class="col-insertion-date"><?= $block->escapeHtml(__('Insertion Date')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($collection as $item): ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col-id">
                    <?= $item->getId(); ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Order ID')) ?>" class="col-order-id">
                    <?= $item->getOrderId(); ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Comment')) ?>" class="col-comment">
                    <?= $item->getComment(); ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Charge')) ?>" class="col-charge">
                    <?php if ($item->getCoins()<0){ echo '<span class="price" style="color:red">' . $item->getCoins() . '</span>'; }
                    else { echo '<span class="price" style="color:green">+' . $item->getCoins() . '</span>';} ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Insertion Date')) ?>" class="col-insertion-date">
                    <?= $item->getInsertionDate(); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
